config/routes.rb
MidnightRiders::Application.routes.draw do
  get 'stylesheets/club', constraints: { format: :css }

  # resources :players

  # resources :mot_ms, path: 'motm', only: [:index]

  # resources :matches do
  #   collection do
  #     get :sync
  #   end
  #   resources :mot_ms, path: 'motm', except: %i(index show)
  #   resources :rev_guesses, path: 'revguess', except: %i(index show destroy)
  #   post 'pick_ems/vote', to: 'pick_ems#vote', as: :pick_em_vote
  # end

  # resources :polls do
  #   member do
  #     post :vote
  #   end
  # end

  # resources :clubs

  # devise_for :users, controllers: { registrations: 'registrations' }
  # resources :users do
  #   collection do
  #     post :import
  #   end
  #   resources :memberships, controller: 'memberships', type: 'Individual', only: %i(index show new create destroy)
  #   resources :memberships, controller: 'memberships', type: 'Family', only: %i(index show new create destroy) do
  #     resources :relatives, type: 'Relative', only: %i(new create destroy) do
  #       member do
  #         post :accept_invitation, as: :accept_invitation_for
  #       end
  #     end
  #   end
  # end

  # get 'downloads/:filename', to: 'downloads#show', as: :download

  # match 'users/:user_id/memberships/:id/cancel', to: 'memberships#cancel', as: :cancel_user_membership, via: %i(put patch)

  # get 'home', to: 'users#home', as: :user_home

  # get 'standings', to: 'static_pages#standings'
  # get 'transactions', to: 'static_pages#transactions'
  # get 'faq', to: 'static_pages#faq'
  # get 'contact', to: 'static_pages#contact'

  match 'memberships/webhooks', to: 'memberships#webhooks', via: :all

  # post 'nominate', to: 'static_pages#nominate'
  devise_for :users, skip: :all

  as :user do
    namespace :api, constraints: { format: :json } do
      get :user, to: 'users#current', as: :current_user
      resources :users

      scope :sessions, controller: :sessions, as: :sessions do
        post '/', action: :create
        delete '/', action: :destroy
      end

      resources :clubs, only: %i[index show]

      resources :matches, only: %i[index show] do
        collection do
          get :next_revs_match
        end
      end

      scope :purchases, controller: :purchases, as: :purchases do
        get :products, action: :products
        post 'payment-intent', action: :create_payment_intent
      end
    end
  end

  get '*path', to: 'static_pages#spa'

  root to: 'static_pages#spa'
end

app/controllers/static_pages_controller.rb
# Controller for static pages – home, faq, contact. Only visible
class StaticPagesController < ActionController::Base

  # authorize_resource class: false, only: %i[standings transactions nominate]

  # # Root path. Shows sign_in if not signed in, user_home if signed in
  # def home
  #   redirect_to user_signed_in? ? user_home_path : new_user_session_path
  # end

  # # Frequently Asked Questions
  # def faq
  # end

  # # TODO: Fill out Contact

  # # Basic contact information
  # def contact
  # end

  # # Shows standings for Pick 'Em and RevGuess.
  # def standings
  #   @season = params.fetch(:season, Date.current.year)
  #   @rev_guess_standings = User.rev_guess_scores(@season).where('(SELECT COUNT(*) FROM rev_guesses LEFT JOIN matches ON rev_guesses.match_id = matches.id WHERE rev_guesses.user_id = users.id AND EXTRACT(YEAR FROM matches.kickoff)=? AND rev_guesses.score IS NOT NULL) > 0', @season).order('rev_guesses_score DESC, rev_guesses_count ASC, username ASC').paginate(page: params[:rev_guess_p], per_page: 25)
  #   @pick_em_standings = User.pick_em_scores(@season).where('(SELECT COUNT(*) FROM pick_ems LEFT JOIN matches ON pick_ems.match_id = matches.id WHERE pick_ems.user_id = users.id AND EXTRACT(YEAR FROM matches.kickoff)=? AND pick_ems.correct IS NOT NULL) > 0', @season).order('correct_pick_ems DESC, total_pick_ems ASC, username ASC').paginate(page: params[:pick_em_p], per_page: 25)
  # end

  # # Nominate board member
  # def nominate
  #   nomination = params[:nomination]&.permit(:name, :position)&.to_h
  #   UserMailer.new_board_nomination_email(current_user, nomination).deliver_now
  #   redirect_to user_home_path, notice: 'Thank you for your nomination.'
  # rescue ArgumentError => e
  #   redirect_to user_home_path, flash: { alert: e.message }
  # end

  # # Admin-only: view transactions
  # def transactions
  #   view = 'memberships'
  #   case params[:view]
  #   when 'detailed'
  #     require 'will_paginate/array'
  #     @transactions = stripe_events
  #     tokens = @transactions.map { |e| e.data.object.object == 'customer' ? e.data.object.id : e.data.object.try(:customer) }.reject(&:nil?)
  #     @users = User.where(stripe_customer_token: tokens).map { |u| [u.stripe_customer_token, u] }.to_h
  #     view = 'transactions'
  #   when 'all'
  #     @transactions = Membership.unscoped.includes(:user).where.not(type: 'Relative').order(created_at: :desc).paginate(per_page: 25, page: params[:page])
  #   when 'refunded'
  #     @transactions = Membership.refunds.includes(:user).where.not(type: 'Relative').reorder(created_at: :desc).paginate(per_page: 25, page: params[:page])
  #   else
  #     @transactions = Membership.includes(:user).where.not(type: 'Relative').reorder(created_at: :desc).paginate(per_page: 25, page: params[:page])
  #   end

  #   respond_to do |format|
  #     format.html { render view }
  #     format.js { render json: @transactions }
  #   end
  # end

  def spa
    render 'spa', layout: false
  end

  private

  # def stripe_events
  #   events = Stripe::Event.list(limit: 25, starting_after: params[:starting_after])
  #   @has_more = events.has_more
  #   events.data
  # end
end

app/views/static_pages/_transactions_nav.haml
.row.collapse
  .medium-3.columns
    = link_to transactions_path, class: "button small expand #{'success' unless params[:view]}" do
      = icon 'fa-solid', 'plus'
      = icon 'fa-solid', 'users'
      New Memberships
  .medium-3.columns
    = link_to transactions_path(view: 'refunded'), class: "button small expand #{'success' if params[:view] == 'refunded'}" do
      = icon 'fa-solid', 'minus'
      = icon 'fa-solid', 'users'
      Refunded Memberships
  .medium-3.columns
    = link_to transactions_path(view: 'all'), class: "button small expand #{'success' if params[:view] == 'all'}" do
      = icon 'fa-solid', 'users'
      All Memberships
  .medium-3.columns
    = link_to transactions_path(view: 'detailed'), class: "button small expand #{'success' if params[:view] == 'detailed'}" do
      = icon 'fa-solid', 'list-alt'
      Detailed Transactions

app/views/static_pages/contact.html.haml
%h1 Contact

%ul.button-group
  %li
    = mail_to 'info@midnightriders.com', class: 'button' do
      = icon 'fa-regular', 'envelope fa-fw'
      General Inquiries
  %li
    = mail_to 'member-portal-support@midnightriders.com', class: 'button secondary' do
      = icon 'fa-regular', 'at fa-fw'
      Member Portal and Web Inquiries

app/views/static_pages/faq.html.haml
%h1 FAQ
.row
  .medium-4.columns
    %ul
      %li= link_to 'Is my information secure?', '#security'
      %li= link_to 'How do I become a member?', '#signup'
      %li= link_to 'I’m already a member. What’s my username?', '#username'
      %li= link_to 'What’s my password?', '#password'
      %li= link_to 'Can family members have their own logins?', '#relatives'
      %li= link_to 'Do I need to sign in to buy merchandise?', '#merchandise'
      %li= link_to 'I still can’t log in', '#other'

  .medium-8.columns
    %dl
      %dt#security Is my information secure?
      %dd
        %p
          %strong Yes.
          The Member Portal uses SSL to connect with your browser, which means the information you share with us is securely
          encrypted. In addition,
          %em we do not store any of your financial information on our servers.
          Instead, your information is passed on to
          = succeed ',' do
            = link_to 'Stripe', 'https://stripe.com', target: '_blank', class: 'underline'
          a secure payment provider that manages credit cards and hands us a token by which to connect your account to their
          data. The only retrievable information Stripe maintains is the last four digits and expiration of your card, for
          your own reference, and tokens by which we can securely make charges. You will receive a receipt from us and from
          Stripe for every transaction.
      %dt#signup How do I become a member?
      %dd
        %p
          Simple! Just go to the #{link_to 'home page', root_path, class: 'underline'} and click "Sign Up." Once you've created an account,
          you can purchase a membership in one quick step. That’s it! Once you’ve done that, you’re a Midnight Rider, and
          you’ll have access to all of the benefits of being one, including Supporters Lot parking, merchandise discounts,
          and full access to the Member Portal.
      %dt#username I'm already a member. What's my username?
      %dd
        %p
          If you signed up in person at a Riders event this year or last, you were sent a welcome email with your login
          information around the time you signed up. If you’re not the
          %em primary accountholder
          of a Family membership, you do not have an account yet.
          %strong= link_to 'See below', '#relatives', class: 'underline'
          for more information about family members.
          The
          %strong default username
          is your first name and last name with no capital letters and no spaces. For example,
          Jay Heaps would be
          = succeed '.' do
            %strong jayheaps
      %dt#password What’s my password?
      %dd
        %p
          If you signed up in person at a Riders event this year or last, you were sent a welcome email with your login
          information. If you know you have an account but don't remember your password,
          %strong= link_to 'click here', new_user_password_path, class: 'underline'
          to request a password reset email. If you’ve never logged in,
      %dt#relatives Can family members have their own logins?
      %dd
        %p
          Yes! Once you've purchased a Family membership, you may add family members to the membership by inviting them
          from
          - if current_user&.current_member?
            your #{link_to 'Membership page', user_membership_path(current_user, current_user.current_membership)}.
          - else
            the page that details your current membership (accessible from the Home page).
          Your family member will create a new user, or use an existing one, and accept your invitation from their Home
          screen.
      %dt#merchandise Do I need to sign in to buy merchandise?
      %dd
        %p
          Not at this time. Just visit #{link_to 'the shop page', 'http://midnightriders.com/shop', target: '_blank', class: 'underline'} to
          get all your Riders merch.
      %dt#other I still can’t log in.
      %dd
        %p
          If you think you should have an account, and you’ve tried the above solutions (check your username – #{link_to 'see above', '#username', class: 'underline'},
          try #{link_to 'resetting your password', new_user_password_path, class: 'underline'}) and you still can’t log in,
          #{link_to 'send us an email', 'mailto:member-portal-support@midnightriders.com?subject=Member%20Portal%20Access', class: 'underline'}.

app/views/static_pages/memberships.html.haml
- content_for :title, "Transactions: #{params[:view].try(:titleize) || 'New'} Memberships"

%h2 Transactions: #{params[:view].try(:titleize) || 'New'} Memberships

= render 'transactions_nav'

%table
  %thead
    %th Year
    %th User
    %th Type
    %th Privileges
    - if params[:view] == 'all'
      %th Status
    %th.text-right Actions
  %tbody
    - @transactions.each do |membership|
      %tr{ data: { event_id: membership.id } }
        %td= membership.year
        %td
          %strong= link_to membership.user.username, membership.user
          %br
          %small
            %time= membership.created_at.strftime('%m-%d-%Y %I:%M%P')
        %td
          = icon 'fa-solid', 'repeat fa-fw' if membership.subscription?
          = icon 'fa-regular', 'credit-card fa-fw' if membership.stripe_charge_id.present?
          = icon 'fa-solid', 'bolt fa-fw' if membership.override.present?
          = icon 'fa-solid', 'warning fa-fw', title: 'No charge found or override present' unless membership.stripe_charge_id.present? || membership.override.present?
          = membership.type
          - if membership.is_a? Family
            %br
            - if membership.relatives.empty?
              %em No Relatives
            - else
              - membership.relatives.includes(:user).where.not(user_id: nil).each do |relative|
                #{link_to relative.user.username, relative.user},
        %td= membership.privileges.join(', ')
        - if params[:view] == 'all'
          %td
            - if membership.override
              = membership.refunded.nil? ? 'Active' : 'Canceled'
            - else
              = membership.refunded.nil? ? 'Active' : 'Canceled/Refunded'
        %td.text-right
          - if can?(:cancel, membership) && membership.refunded.nil?
            = link_to cancel_user_membership_path(membership.user, membership), class: 'button tiny alert', title: 'Cancel', data: { method: :patch, confirm: "Cancel #{membership.user.username}'s Membership?" } do
              = icon 'fa-solid', 'ban'
          - if can?(:refund, membership) && membership.refunded.nil? && membership.stripe_charge_id.present?
            = link_to cancel_user_membership_path(membership.user, membership, refund: true), class: 'button tiny alert', title: 'Cancel and Refund', data: { method: :patch, confirm: "Cancel and Refund #{membership.user.username}'s Membership?" }  do
              = icon 'fa-solid', 'undo'
.text-right
  = will_paginate(@transactions, previous_label: 'Newer', next_label: 'Older', params: { view: params[:view] })

app/views/static_pages/preact.html.erb
<!DOCTYPE html>
<html lang="en/US">
<head>
<title>Midnight Riders</title>
<link href="https://fonts.googleapis.com/css?family=Lato:300,700" rel="stylesheet" />
<meta charset="utf-8" />
<%= favicon_link_tag 'icons/apple-touch-icon-precomposed-57x57.png', rel: 'apple-touch-icon-precomposed', type: 'image/png' %>
<%= favicon_link_tag 'icons/apple-touch-icon-precomposed-72x72.png', rel: 'apple-touch-icon-precomposed', sizes: '72x72', type: 'image/png' %>
<%= favicon_link_tag 'icons/apple-touch-icon-precomposed-114x114.png', rel: 'apple-touch-icon-precomposed', sizes: '114x114', type: 'image/png' %>
<%= favicon_link_tag 'icons/favicon.ico' %>
<meta content="Midnight Riders Member Portal" name="og:title" />
<meta content="<%= image_url('logo.png') %>" name="og:image" />
<% if Rails.env.production? %>
<%= render partial: 'layouts/ga' %>
<% else %>
<script>if (!window.ga) window.ga = function() {};</script>
<%= vite_client_tag %>
<% end %>
<meta content="initial-scale=1, maximum-scale=1" name="viewport" />
<%= csrf_meta_tags %>
<%= render 'shared/riders_logo' %>
</head>
<body>
<div id="root"></div>
<%= vite_javascript_tag 'application.tsx' %>
</body>
</html>

app/views/static_pages/spa.html.erb
<!DOCTYPE html>
<html lang="en/US">
<head>
<title>Midnight Riders</title>
<link href="https://fonts.googleapis.com/css?family=Lato:300,700" rel="stylesheet" />
<meta charset="utf-8" />
<%= favicon_link_tag 'icons/apple-touch-icon-precomposed-57x57.png', rel: 'apple-touch-icon-precomposed', type: 'image/png' %>
<%= favicon_link_tag 'icons/apple-touch-icon-precomposed-72x72.png', rel: 'apple-touch-icon-precomposed', sizes: '72x72', type: 'image/png' %>
<%= favicon_link_tag 'icons/apple-touch-icon-precomposed-114x114.png', rel: 'apple-touch-icon-precomposed', sizes: '114x114', type: 'image/png' %>
<%= favicon_link_tag 'icons/favicon.ico' %>
<meta content="Midnight Riders Member Portal" name="og:title" />
<meta content="<%= image_url('logo.png') %>" name="og:image" />
<% if Rails.env.production? %>
<%= render partial: 'layouts/ga' %>
<% else %>
<script>if (!window.ga) window.ga = function() {};</script>
<%= vite_client_tag %>
<% end %>
<meta content="width=device-width, initial-scale=1" name="viewport" />
<%= csrf_meta_tags %>
<%= render 'shared/riders_logo' %>
</head>
<body>
<div id="root"></div>
<script src="https://js.stripe.com/v3"></script>
<%= vite_javascript_tag 'application.tsx' %>
</body>
</html>