config/routes.rb
MidnightRiders::Application.routes.draw do
  get 'stylesheets/club', constraints: { format: :css }

  # resources :players

  # resources :mot_ms, path: 'motm', only: [:index]

  # resources :matches do
  #   collection do
  #     get :sync
  #   end
  #   resources :mot_ms, path: 'motm', except: %i(index show)
  #   resources :rev_guesses, path: 'revguess', except: %i(index show destroy)
  #   post 'pick_ems/vote', to: 'pick_ems#vote', as: :pick_em_vote
  # end

  # resources :polls do
  #   member do
  #     post :vote
  #   end
  # end

  # resources :clubs

  # devise_for :users, controllers: { registrations: 'registrations' }
  # resources :users do
  #   collection do
  #     post :import
  #   end
  #   resources :memberships, controller: 'memberships', type: 'Individual', only: %i(index show new create destroy)
  #   resources :memberships, controller: 'memberships', type: 'Family', only: %i(index show new create destroy) do
  #     resources :relatives, type: 'Relative', only: %i(new create destroy) do
  #       member do
  #         post :accept_invitation, as: :accept_invitation_for
  #       end
  #     end
  #   end
  # end

  # get 'downloads/:filename', to: 'downloads#show', as: :download

  # match 'users/:user_id/memberships/:id/cancel', to: 'memberships#cancel', as: :cancel_user_membership, via: %i(put patch)

  # get 'home', to: 'users#home', as: :user_home

  # get 'standings', to: 'static_pages#standings'
  # get 'transactions', to: 'static_pages#transactions'
  # get 'faq', to: 'static_pages#faq'
  # get 'contact', to: 'static_pages#contact'

  match 'memberships/webhooks', to: 'memberships#webhooks', via: :all

  # post 'nominate', to: 'static_pages#nominate'
  devise_for :users, skip: :all

  as :user do
    namespace :api, constraints: { format: :json } do
      get :user, to: 'users#current', as: :current_user
      resources :users

      scope :sessions, controller: :sessions, as: :sessions do
        post '/', action: :create
        delete '/', action: :destroy
      end

      resources :clubs, only: %i[index show]

      resources :matches, only: %i[index show] do
        collection do
          get :next_revs_match
        end
      end

      scope :purchases, controller: :purchases, as: :purchases do
        get :products, action: :products
        post 'payment-intent', action: :create_payment_intent
      end
    end
  end

  get '*path', to: 'static_pages#spa'

  root to: 'static_pages#spa'
end

app/controllers/rev_guesses_controller.rb
# Controller for +RevGuess+ model.
class RevGuessesController < ApplicationController
  load_and_authorize_resource through: :current_user
  before_action :set_match

  # GET /rev_guesses/new
  def new
    @rev_guess = RevGuess.new
  end

  # GET /rev_guesses/1/edit
  def edit
  end

  # POST /rev_guesses
  # POST /rev_guesses.json
  def create
    @rev_guess = RevGuess.new(rev_guess_params)

    respond_to do |format|
      if @rev_guess.save
        format.html { redirect_to matches_url(date: @match.kickoff.to_date), notice: 'RevGuess was successfully created.' }
        format.json { render action: 'show', status: :created, location: @rev_guess }
      else
        format.html { render action: 'new' }
        format.json { render json: @rev_guess.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rev_guesses/1
  # PATCH/PUT /rev_guesses/1.json
  def update
    respond_to do |format|
      if @rev_guess.update(rev_guess_params)
        format.html { redirect_to matches_url(date: @match.kickoff.to_date), notice: 'RevGuess was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @rev_guess.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_match
    @match = Match.with_clubs.find(params[:match_id])
  end

  # Never trust parameters from the scary internet, only allow the allowlist through.
  def rev_guess_params
    params.require(:rev_guess).permit(:match_id, :user_id, :home_goals, :away_goals, :comment)
  end
end

app/views/rev_guesses/_form.html.haml
= render partial: 'shared/match_info', locals: { match: @match }
= form_for [@match, @rev_guess] do |f|
  - if @rev_guess.errors.any?
    .alert-box.alert
      - @rev_guess.errors.full_messages.each do |msg|
        = msg
        %br

  = f.hidden_field :user_id, value: current_user.id
  = f.hidden_field :match_id, value: @match.id
  .row
    .medium-8.medium-centered.columns
      .row
        .small-6.columns
          = f.label :home_goals, @match.home_team.abbrv, class: 'text-center'
          = f.number_field :home_goals, class: 'text-center', value: (@rev_guess.home_goals || 0), min: 0, pattern: '\d*'
        .small-6.columns
          = f.label :away_goals, @match.away_team.abbrv, class: 'text-center'
          = f.number_field :away_goals, class: 'text-center', value: (@rev_guess.away_goals || 0), min: 0, pattern: '\d*'
      .row
        .large-3.columns
          = f.label :comment, class: 'inline'
        .large-9.columns
          = f.text_field :comment
      .actions.text-right
        = link_to 'Back', matches_path(date: @match.kickoff.to_date)
        = f.button :submit, class: 'button' do
          = icon 'fa-regular', 'check'
          = f.object.new_record? ? 'Vote' : 'Update'