config/routes.rb
MidnightRiders::Application.routes.draw do
  get 'stylesheets/club', constraints: { format: :css }

  # resources :players

  # resources :mot_ms, path: 'motm', only: [:index]

  # resources :matches do
  #   collection do
  #     get :sync
  #   end
  #   resources :mot_ms, path: 'motm', except: %i(index show)
  #   resources :rev_guesses, path: 'revguess', except: %i(index show destroy)
  #   post 'pick_ems/vote', to: 'pick_ems#vote', as: :pick_em_vote
  # end

  # resources :polls do
  #   member do
  #     post :vote
  #   end
  # end

  # resources :clubs

  # devise_for :users, controllers: { registrations: 'registrations' }
  # resources :users do
  #   collection do
  #     post :import
  #   end
  #   resources :memberships, controller: 'memberships', type: 'Individual', only: %i(index show new create destroy)
  #   resources :memberships, controller: 'memberships', type: 'Family', only: %i(index show new create destroy) do
  #     resources :relatives, type: 'Relative', only: %i(new create destroy) do
  #       member do
  #         post :accept_invitation, as: :accept_invitation_for
  #       end
  #     end
  #   end
  # end

  # get 'downloads/:filename', to: 'downloads#show', as: :download

  # match 'users/:user_id/memberships/:id/cancel', to: 'memberships#cancel', as: :cancel_user_membership, via: %i(put patch)

  # get 'home', to: 'users#home', as: :user_home

  # get 'standings', to: 'static_pages#standings'
  # get 'transactions', to: 'static_pages#transactions'
  # get 'faq', to: 'static_pages#faq'
  # get 'contact', to: 'static_pages#contact'

  match 'memberships/webhooks', to: 'memberships#webhooks', via: :all

  # post 'nominate', to: 'static_pages#nominate'
  devise_for :users, skip: :all

  as :user do
    namespace :api, constraints: { format: :json } do
      get :user, to: 'users#current', as: :current_user
      resources :users

      scope :sessions, controller: :sessions, as: :sessions do
        post '/', action: :create
        delete '/', action: :destroy
      end

      resources :clubs, only: %i[index show]

      resources :matches, only: %i[index show] do
        collection do
          get :next_revs_match
        end
      end

      scope :purchases, controller: :purchases, as: :purchases do
        get :products, action: :products
        post 'payment-intent', action: :create_payment_intent
      end
    end
  end

  get '*path', to: 'static_pages#spa'

  root to: 'static_pages#spa'
end

app/controllers/api/matches_controller.rb
class Api::MatchesController < ApiController
  skip_before_action :authenticate_user!, only: %i[next_revs_match]

  def next_revs_match
    @match = revs&.next_match
    render 'show'
  end

  def show
    authorize! :read, Match

    @match = Match.find(params[:id])
  end

  # TODO: match filtering
  def index
    authorize! :read, Match

    @start_date = (params[:date]&.in_time_zone(Time.zone) || Time.current).beginning_of_week
    @matches = Match.unscoped.with_clubs.includes(:pick_ems).where(kickoff: (@start_date..@start_date + 7.days)).order(kickoff: :asc, location: :asc)
    @prev_link = "Previous #{'Game ' if @matches.empty?}Week"
    @next_link = "Next #{'Game ' if @matches.empty?}Week"
    @prev_date = @matches.empty? ? Match.unscoped.where('kickoff < ?', Time.current).order(kickoff: :asc).last&.kickoff : @start_date - 1.week
    @prev_date = @prev_date&.to_date
    @next_date = @matches.empty? ? Match.unscoped.where('kickoff > ?', Time.current).order(kickoff: :asc).first&.kickoff : @start_date + 1.week
    @next_date = @next_date&.to_date
    @is_current_week = @start_date == Time.current.beginning_of_week
  end
end

app/controllers/matches_controller.rb
require 'net/http'

# Controller for +Match+ model.
class MatchesController < ApplicationController
  authorize_resource
  before_action :set_match, only: %i(show edit update destroy)
  before_action :check_for_matches_to_update, only: %i(auto_update)

  # GET /matches
  # GET /matches.json
  # GET /matches.svg
  # WIP: GET /matches.png
  def index
    @start_date = (params[:date].try(:in_time_zone, Time.zone) || Time.current).beginning_of_week
    @matches = Match.unscoped.with_clubs.includes(:pick_ems).where(kickoff: (@start_date..@start_date + 7.days)).order(kickoff: :asc, location: :asc)
    @prev_link = "Previous #{'Game ' if @matches.empty?}Week"
    @next_link = "Next #{'Game ' if @matches.empty?}Week"
    @prev_date = @matches.empty? ? Match.unscoped.where('kickoff < ?', Time.current).order(kickoff: :asc).last.try(:kickoff) : @start_date - 1.week
    @prev_date = @prev_date.try(:to_date)
    @next_date = @matches.empty? ? Match.unscoped.where('kickoff > ?', Time.current).order(kickoff: :asc).first.try(:kickoff) : @start_date + 1.week
    @next_date = @next_date.try(:to_date)
    @is_current_week = @start_date == Time.current.beginning_of_week
    respond_to do |format|
      format.html
      format.json
      format.svg {
        redirect_to matches_url unless current_user.privilege? 'admin'
        render layout: false, cached: false
      }
      # WIP: easily-reusable PNG generation from SVG
      # format.png {
      #   @embed_resources = true
      #   redirect_to matches_url unless current_user.privilege? 'admin'
      #   svg_str = render_to_string 'matches/index', layout: false, formats: %w[svg]
      #   img = Magick::Image.from_blob(svg_str) {
      #     self.background_color = '#6a0003'
      #     self.density= '144.0x144.0'
      #     self.format = 'SVG'
      #   }
      #   png = img[0].to_blob {
      #     self.density= '144.0x144.0'
      #     self.format = 'PNG'
      #   }
      #   send_data png, filename: "matches-#{@start_date.strftime('%Y-%m-%d')}.png", disposition: 'inline', type: 'image/png'
      # }
    end
  end

  # GET /matches/1
  # GET /matches/1.json
  def show
    @order_point = @match.order_selected(Match.all_seasons)
    @mot_m_players = Player.includes(:mot_m_firsts, :mot_m_seconds, :mot_m_thirds).select { |x| x.mot_m_total(match_id: @match.id) && x.mot_m_total(match_id: @match.id) > 0 }.sort_by { |x| x.mot_m_total(match_id: @match.id) }.reverse if @match.teams.include? revs
  end

  # GET /matches/sync
  def sync
    year = Date.current > Date.current.end_of_year - 15.days ? Date.current.year + 1 : Date.current.year
    uri = URI.parse("https://v3.football.api-sports.io/fixtures?league=253&season=#{year}")
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true
    request = Net::HTTP::Get.new(uri)
    request['x-apisports-key'] = ENV['API_FOOTBALL_KEY']
    resp = http.request(request)

    match_data = JSON.parse(resp.read_body, symbolize_names: true)[:response]
    clubs = Club.all.map { |c| [c.api_id, c] }.to_h
    errors = []
    changed = 0
    added = 0
    match_data.each do |data|
      match = Match.find_or_initialize_by(uid: data[:fixture][:id]) do |m|
        m.home_team = clubs[data[:teams][:home][:id]]
        m.away_team = clubs[data[:teams][:away][:id]]
        m.location = data[:fixture][:venue][:name].presence || clubs[data[:teams][:home][:id]].name
      end
      match.season = year
      match.kickoff = Time.zone.parse(data[:fixture][:date])
      if data[:fixture][:status][:short].in? %w[FT AET PEN]
        match.home_goals = data[:goals][:home]
        match.away_goals = data[:goals][:away]
      end
      added += 1 if match.new_record?
      changed += 1 if !match.new_record? && match.changed?
      errors += match.errors.full_messages.map { |m| "#{data[:id]}: #{m}" } unless match.save
    end
    flash[:notice] = "#{match_data.length} matches synced: #{added} added, #{changed} changed."
    flash[:alert] = errors.join(', ') if errors.any?
    redirect_to matches_path
  end

  # GET /matches/new
  def new
    @match = Match.new
  end

  # GET /matches/1/edit
  def edit; end

  # POST /matches
  # POST /matches.json
  def create
    @match = Match.new(match_params)

    respond_to do |format|
      if @match.save
        format.html { redirect_to @match, notice: 'Match was successfully created.' }
        format.json { render action: 'show', status: :created, location: @match }
      else
        format.html { render action: 'new' }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1
  # PATCH/PUT /matches/1.json
  def update
    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to matches_path(date: @match.kickoff.to_date), notice: 'Match was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match.destroy
    respond_to do |format|
      format.html { redirect_to matches_url }
      format.json { head :no_content }
    end
  end

  private

  def check_for_matches_to_update
    redirect_to matches_path, flash: { notice: 'There were no matches to update.' } if matches_to_update.empty?
  end

  def matches_to_update
    @finished_matches_to_update ||= Match.where('(home_goals IS NULL OR away_goals IS NULL) AND kickoff < ?', Time.current - 2.hours)
  end

  def matches_to_update_by_week
    matches_to_update.group_by { |m| m.kickoff.to_date.beginning_of_week }
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_match
    @match = Match.all_seasons.with_clubs.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the allowlist through.
  def match_params
    params.require(:match).permit(:home_team_id, :away_team_id, :kickoff, :kickoff_date, :kickoff_time, :location, :home_goals, :away_goals)
  end

  def scrape_all_results_for_week(html)
    matches = html.css('.ml-link')
    matches.map { |match| scrape_single_result(match) }
  end

  def scrape_single_result(match)
    return {} unless match.at_css('.sb-match-date').try(:content).present?
    result = { date: match.at_css('.sb-match-date').content.to_date }
    %w(home away).each do |team|
      data = match.at_css(".sb-#{team}")
      result[team.to_sym] = {
        team: data.at_css('.sb-club-name-short').content,
        goals: data.at_css('.sb-score').present? ? data.at_css('.sb-score').content.to_i : nil
      }
    end
    result
  end
end

app/helpers/matches_helper.rb
module MatchesHelper
  def png_asset(path)
    return image_url(path) unless @embed_resources

    "data:image/png;base64,#{Base64.strict_encode64(Rails.application.assets.load_path.find(path).html_safe)}"
  end
end

app/views/matches/_form.html.haml
= form_for @match do |f|
  - if @match.errors.any?
    #error_explanation
      %h2= "#{pluralize(@match.errors.count, 'error')} prohibited this match from being saved:"
      %ul
        - @match.errors.full_messages.each do |msg|
          %li= msg

  .row
    .large-8.columns.right
      .row
        .medium-6.columns
          = f.label :home_team_id
          = f.select :home_team_id, options_for_select(Club.all.map{|c| [c.name,c.id] },f.object.home_team_id)
        .medium-6.columns
          = f.label :away_team_id
          = f.select :away_team_id, options_for_select(Club.all.map{|c| [c.name,c.id] },f.object.away_team_id)
  .row
    .large-4.columns
      = f.label :kickoff
    .large-8.columns
      .row
        .small-6.columns
          = f.text_field :kickoff_date, value: f.object.kickoff.try(:to_date), type: 'date'
        .small-6.columns
          = f.text_field :kickoff_time, value: f.object.kickoff.try(:strftime, '%H:%M'), type: 'time'
  .row
    .large-4.columns
      = f.label :location
    .large-8.columns
      = f.text_field :location
  .row
    .large-8.columns.right
      .row
        .small-6.columns
          = f.label :home_goals
          = f.number_field :home_goals, pattern: '\d*', min: 0, max: 50
        .small-6.columns
          = f.label :away_goals
          = f.number_field :away_goals, pattern: '\d*', min: 0, max: 50
  .row.actions
    .column.text-right
      = f.button :submit, class: 'button' do
        = icon 'fa-regular', 'check'
        = f.object.new_record? ? 'Create' : 'Update'

app/views/matches/_match.html.haml
- match = match.decorate
- small ||= false
%li.match{ class: "#{'pending' unless match.complete?} #{'highlight' if match.teams.include?(revs) && !small }"}
  %time{ datetime: match.kickoff.xmlschema }
    = link_to match do
      = match.kickoff.strftime('%_m.%-d %l:%M%P')
      = icon 'fa-solid', 'circle-arrow-right fa-fw'
  .score
    - unless match.in_future?
      = match.home_team.abbrv if match.complete?
      = match.score
      = match.away_team.abbrv if match.complete?
  .pick-em
    = match.pick_em_buttons
    = match.pick_em_sub
  .location
    = match.location
  - if match.teams.include? revs
    = match.rev_guess_button('small expand') if match.in_future?
    = match.mot_m_button('small expand') if match.voteable?

app/views/matches/_small.html.haml
.table
  .thead
    .tr
      .td.text-center
        = icon 'fa-regular', 'certificate'
        Pick ’Em
      .td Match / time
  - matches.each do |m|
    - m = m.decorate
    .tr
      .td.small-6.columns.text-right
        = m.pick_em_buttons
      .td.small-6.columns.secondary-border.border-left{class: m.home_team.abbrv.downcase}
        = link_to m do
          = m.home_team.abbrv
          %small{ title: 'W-L-D' } (#{m.away_team.record})
          v
          = m.away_team.abbrv
          %small{ title: 'W-L-D' } (#{m.away_team.record})
          - if m.complete?
            = surround '(', ')' do
              = m.score
          %small
            %br
            = succeed ',' do
              = m.kickoff.strftime('%_m.%-d %l:%M%P')
            = m.location

app/views/matches/index.html.haml
- content_for :title, 'Match listings for the week of ' + @start_date.strftime('%_m.%-d.%Y')

.row.actions
  .medium-8.columns{ class: ('medium-centered' unless can?(:manage, Match)) }
    %ul.button-group
      - if @prev_date
        %li{ class: "small-#{@is_current_week ? '6' : '4'}" }
          = link_to matches_path(date: @prev_date), class: 'button secondary small expand' do
            = icon 'fa-solid', 'circle-arrow-left fa-fw'
            = @prev_link
      - unless @is_current_week
        %li.small-4
          = link_to matches_path, class: 'button small expand' do
            = icon 'fa-regular', 'calendar fa-fw'
            This Week
      - if @next_date
        %li{ class: "small-#{@is_current_week ? '6' : '4'}" }
          = link_to matches_path(date: @next_date), class: 'button secondary small expand' do
            = @next_link
            = icon 'fa-solid', 'circle-arrow-right fa-fw'
  - if can? :manage, Match
    .medium-4.columns.text-right
      = link_to '#', class: 'button small expand', data: { reveal_id: 'matches-admin' } do
        = icon 'fa-solid', 'bolt fa-fw'
        Admin
      #matches-admin.reveal-modal.small{ data: { reveal: true } }
        %a.close-reveal-modal{ href: '#' } &times;
        %h2 Matches Admin
        .row
          .medium-8.columns.right
            = link_to sync_matches_path, class: 'button small secondary expand' do
              = icon 'fa-solid', 'refresh fa-fw'
              Sync Fixtures/Results
        .row
          .medium-8.columns.right
            = link_to new_match_path, class: 'button small expand' do
              = icon 'fa-regular', 'calendar fa-fw'
              New Match

- if @matches.present?
  .row
    .large-3.columns
      %h2 Matches for the week of #{@start_date.strftime('%_m.%-d.%Y')}
      .show-for-medium-up
        %p Make your <strong>Pick ’Em</strong> picks by clicking on the crest of the team you expect to win, or D for Draw.
        %p To submit your <strong>RevGuess</strong>, click on the button underneath any Revs game before kickoff.
        %p
          And don’t forget to come back after every game to vote for your Man of the Match –
          voting for <strong>Man of the Match</strong> is tallied at the end of every year for the Riders’ annual
          <a href="https://www.midnightriders.com/events-awards/man-of-the-year-award/">Man of the Year</a> award.
    .large-9.columns
      %ul.matches
        = render @matches
- else
  .alert-box
    %h2.text-center No matches scheduled this week

app/views/matches/show.html.haml
.row
  .small-4.medium-3.large-2.columns
    - if @order_point.previous(false)
      = link_to @order_point.previous(false), class: "button small expand primary-bg #{@order_point.previous(false).home_team.abbrv.downcase}" do
        = icon 'fa-regular', 'arrow-left'
        = @order_point.previous(false).home_team.abbrv
        v
        = @order_point.previous(false).away_team.abbrv
        = @order_point.previous(false).kickoff.strftime('%_m.%-d')
  .small-4.medium-6.large-8.columns.text-center
    = link_to matches_path(date: @match.kickoff.to_date), class: 'button small' do
      = icon 'fa-regular', 'calendar fa-fw'
      Back
  .small-4.medium-3.large-2.columns.right
    - if @order_point.next(false)
      = link_to @order_point.next(false), class: "button small expand primary-bg #{@order_point.next(false).home_team.abbrv.downcase}" do
        = @order_point.next(false).home_team.abbrv
        v
        = @order_point.next(false).away_team.abbrv
        = @order_point.next(false).kickoff.strftime('%_m.%-d')
        = icon 'fa-regular', 'arrow-right'
.row.collapse
  .medium-5.large-5.columns
    %h2.primary-bg.secondary-border.border-bottom.thick.text-right{ class: @match.home_team.abbrv.downcase }
      %small{ title: 'W-L-D' } (#{@match.home_team.record})
      = @match.home_team.name
  .medium-2.columns.text-center
    %h2= @match.score
  .medium-5.large-5.columns
    %h2.primary-bg.secondary-border.border-bottom.thick{ class: @match.away_team.abbrv.downcase }
      = @match.away_team.name
      %small{ title: 'W-L-D' } (#{@match.away_team.record})
.row
  .medium-8.columns
    %h3.subheader
      = @match.kickoff.strftime('%A, %_m.%-d.%Y at %l:%M%P %Z')
      at
      = @match.location
  .medium-4.columns.right.text-right
    - if @match.teams.include?(revs)
      - if @match.kickoff.future?
        = link_to rev_guess_path_for(@match), class: 'button small' do
          = icon 'fa-regular', 'question'
          RevGuess
      - elsif @match.kickoff + 45.minutes < Time.current && @match.teams.include?(revs)
        = link_to mot_m_path_for(@match), class: 'button small' do
          = icon 'fa-regular', 'list-ol'
          = (mot_m_for(@match) ? 'Change' : 'Cast')
          MotM Vote
    - if can? :edit, @match
      = link_to edit_match_path(@match), class: 'button secondary small' do
        = icon 'fa-regular', 'pencil'
        Edit


.row
  .medium-8.medium-centered.columns
    %h2 Pick ’Ems
    - picks = @match.pick_ems.length
    - home_picks = @match.pick_ems.select{|x| x.result == PickEm::RESULTS[:home]}.length
    - draw_picks = @match.pick_ems.select{|x| x.result == PickEm::RESULTS[:draw]}.length
    - away_picks = @match.pick_ems.select{|x| x.result == PickEm::RESULTS[:away]}.length
    - if picks > 0
      .table.pick-em-results
        .tr
          - if home_picks > 0
            .td.primary-bg.text-center{ class: @match.home_team.abbrv.downcase, style: "width:#{(home_picks.to_f/picks) * 100}%" }
              - if @match.home_team.crest.blank?
                = @match.home_team.abbrv
              - else
                = image_tag(@match.home_team.crest.url(:thumb), class: 'crest-img', alt: @match.home_team.abbrv)
              %small
                (#{home_picks}/#{picks})
          - if draw_picks > 0
            .td.text-center{ style: "width: #{(draw_picks.to_f/picks) * 100}%" }
              D
              %small
                (#{draw_picks}/#{picks})
          - if away_picks > 0
            .td.primary-bg.text-center{ class: @match.away_team.abbrv.downcase, style: "width: #{(away_picks.to_f/picks) * 100}%" }
              - if @match.away_team.crest.blank?
                = @match.away_team.abbrv
              - else
                = image_tag(@match.away_team.crest.url(:thumb), class: 'crest-img', alt: @match.away_team.abbrv)
              %small
                (#{away_picks}/#{picks})
    - else
      %h4 No picks yet


    - if @match.teams.include?(revs)
      %h3 Man of the Match Standings
      %ul.table
        - if @mot_m_players.empty?
          %li.tr
            .td No votes cast yet
        - else
          .thead
            %li.tr
              .thd
              .thd Player
              .thd.numeric 1
              .thd.numeric 2
              .thd.numeric 3
          - place = 0
          - last = nil
          - @mot_m_players.each do |mot_m|
            %li.tr
              .td.numeric= last == mot_m.mot_m_total ? '' : (place += 1)
              .td
                %p
                  = mot_m.first_name
                  %strong= mot_m.last_name
              .td
                %p= mot_m.mot_m_firsts.where(match: @match).length
              .td
                %p= mot_m.mot_m_seconds.where(match: @match).length
              .td
                %p= mot_m.mot_m_thirds.where(match: @match).length
      %h3 RevGuesses
      %ul.table
        .thead
          %li.tr
            .thd User
            .thd.text-center Score
            .thd Comment
        - @match.rev_guesses.sort_by{|r| r.user.username}.each do |r|
          %li.tr
            .td
              %p.nowrap
                = link_to r.user do
                  = image_tag(r.user.gravatar, class: 'gravatar', alt: 'gravatar')
                  = r.user.username
            .td.text-center
              %p
                %strong
                  = r.home_goals
                  \–
                  = r.away_goals
            .td
              %p= r.comment